version: '3.3'

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:8282:80
    volumes:
      - .:/var/www:delegated
      - ./dev.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated
    links:
      - db
    env_file:
      - .env.local
    environment:
      APP_ENV: prod
    deploy:
      resources:
        limits:
          memory: 100M
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=symfony
    ports:
      - 127.0.0.1:3350:3306
    deploy:
      resources:
        limits:
          cpus: "0.02"
          memory: 100M
volumes:
  db-data:
    driver: local
