version: '3.3'
services:
  phptest:
    build:
      context: ./tools/docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
    networks:
      - test
    env_file: .env.test
  dbtest:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    networks:
      - test

networks:
  test:
