version: '3.3'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=symfony
    ports:
      - 3306:3306
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: galkaev
    links:
      - db
    ports:
      - 8080:8080
volumes:
  db-data:
    driver: local
